{"name": "Можно авторизоваться с неверным name в теле запроса", "status": "passed", "start": 1719835350574, "stop": 1719835351293, "uuid": "6bd1d96c-abe7-426f-9098-e15b0face820", "historyId": "1d178a76c855d5bc7e8f5521a99bcdd2", "testCaseId": "1d178a76c855d5bc7e8f5521a99bcdd2", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_incorrect_name_code_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "14036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}